[package]
name = "countserver"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.15"

[dependencies.tokio]
version = "1.6.1"
optional = true

[dependencies.async-std]
version = "1.9.0"
optional = true
